# Stage 1: Build React
FROM node:20 AS react-client
WORKDIR /app
COPY src/react-client/package*.json ./
RUN npm install
COPY src/react-client .
RUN npm run build

# Stage 2: Web server
FROM node:20
WORKDIR /app

RUN apt-get update && apt-get install -y curl

COPY src/web_server/package*.json ./
RUN npm install
COPY src/web_server .

#  This line copies the React build into the server
COPY --from=react-client /app/build ./client/build

EXPOSE 8080
CMD ["node", "app.js"]
