FROM gcc:13

# Install CMake and Git
RUN apt-get update && apt-get install -y cmake git && rm -rf /var/lib/apt/lists/*

WORKDIR /server
COPY . .
RUN mkdir -p build && cd build && cmake .. && make

# Run server with default params (you can override with `docker run`)
CMD ["./build/server", "12345", "1000", "3"]