version: '3'

services:
  bloom_filter_tests:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    working_dir: /app
    command: >
      bash -c "
        cd build && 
        cmake .. && 
        make && 
        ./src/tests/storage_test/storage_tests
      "